# -*- coding: utf-8 -*-
"""ExercíciosPY1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zg_onDaWOG3Eu0FjHpBxBGFwrl9M7-1
"""

nome = input ("Digite seu primeiro nome = ")
sobrenome = input  ("Digite seu sobrenome = ")
print (nome + sobrenome)

numero1 = 25
numero2 = 2

print (numero1 ** numero2)

n1  = int (input ("Digite um número inteiro"))
n2 = int (input  ("Digite outro número inteiro"))
s = n1 + n2
print (s)

py = ("Phyton")
n1 = int (input('Digite um número='))
print (py , n1)

n1  = int (input ("Digite um número inteiro"))
n2 = int (input  ("Digite outro número inteiro"))
s = n1 + n2
print ("A soma entre {} e {} é igual a {}".format(n1,n2,s))